/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/magic_forest.glb 
Author: WanderCris (https://sketchfab.com/WanderCris)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magic-forest-15adb44385ea4473ba57308ab32ab768
Title: Magic Forest
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/magic_forest.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[27.201, 196.988, -21.705]} rotation={[-1.599, 0.006, -0.004]} scale={[2263.194, 2263.193, 2520.438]}>
        <mesh geometry={nodes.Icosphere_Tierra1_0.geometry} material={materials.Tierra1} />
        <mesh geometry={nodes.Icosphere_Tierra2_0.geometry} material={materials.Tierra2} />
        <mesh geometry={nodes.Icosphere_GRASS_0.geometry} material={materials.GRASS} />
      </group>
      <group position={[1236.04, -1705.084, -958.353]} rotation={[-Math.PI / 2, 0, 0]} scale={[280.976, 280.976, 504.849]}>
        <mesh geometry={nodes.Icosphere001_Tierra1_0.geometry} material={materials.Tierra1} />
        <mesh geometry={nodes.Icosphere001_GRASS_0.geometry} material={materials.GRASS} />
      </group>
      <group position={[-715.027, 87.338, 2337.363]} rotation={[-1.521, 0.03, 1.803]} scale={394.791}>
        <mesh geometry={nodes.Icosphere004_Tierra1_0.geometry} material={materials.Tierra1} />
        <mesh geometry={nodes.Icosphere004_Tierra2_0.geometry} material={materials.Tierra2} />
        <mesh geometry={nodes.Icosphere004_GRASS_0.geometry} material={materials.GRASS} />
      </group>
      <mesh geometry={nodes.Icosphere002_Tierra1_0.geometry} material={materials.Tierra1} position={[-1413.118, -2367.549, 1247.82]} rotation={[-Math.PI / 2, 0, 1.78]} scale={368.308} />
      <mesh geometry={nodes.Icosphere003_Tierra1_0.geometry} material={materials.Tierra1} position={[-1173.304, -2902.296, -514.072]} rotation={[-Math.PI / 2, 0, 0]} scale={[269.913, 269.913, 368.043]} />
      <mesh geometry={nodes.Icosphere005_Tierra1_0.geometry} material={materials.Tierra1} position={[-328.005, -1170.187, -1872.328]} rotation={[2.931, 0.404, -0.066]} scale={[96.268, 96.268, 131.268]} />
      <mesh geometry={nodes.Icosphere006_Tierra1_0.geometry} material={materials.Tierra1} position={[-940.434, -1484.172, 1997.716]} rotation={[-0.835, -0.088, 0.104]} scale={[55.179, 55.179, 75.241]} />
      <mesh geometry={nodes.Icosphere007_Tierra1_0.geometry} material={materials.Tierra1} position={[157.949, -3258.558, 471.826]} rotation={[-1.628, -0.113, -0.187]} scale={[96.268, 96.268, 131.268]} />
      <mesh geometry={nodes.Icosphere008_Tierra1_0.geometry} material={materials.Tierra1} position={[-2261.377, -273.373, 463.607]} rotation={[2.931, 0.404, -0.066]} scale={[72.5, 72.5, 98.859]} />
      <mesh geometry={nodes.Icosphere009_Tierra2_0.geometry} material={materials.Tierra2} position={[1101.863, -2319.861, 498.509]} rotation={[Math.PI / 2, 0, 0]} scale={[-18.507, 18.507, 33.252]} />
      <mesh geometry={nodes.Icosphere010_Tierra1_0.geometry} material={materials.Tierra1} position={[701.272, -596.797, 2016.011]} rotation={[Math.PI / 2, 0, 0]} scale={[-18.507, 18.507, 33.252]} />
      <mesh geometry={nodes.Icosphere011_Tierra1_0.geometry} material={materials.Tierra1} position={[1160.427, -1109.519, -1271.553]} rotation={[Math.PI / 2, 0, 0]} scale={[-18.507, 18.507, 33.252]} />
      <mesh geometry={nodes.Icosphere012_Tierra1_0.geometry} material={materials.Tierra1} position={[-2003.724, -693.522, -719.844]} rotation={[Math.PI / 2, 0, 0]} scale={[-18.507, 18.507, 33.252]} />
      <mesh geometry={nodes.Icosphere013_Tierra1_0.geometry} material={materials.Tierra1} position={[534.604, -1696.749, 2025.176]} rotation={[Math.PI / 2, 0, 0]} scale={[-18.507, 18.507, 33.252]} />
      <mesh geometry={nodes.Icosphere014_Tierra1_0.geometry} material={materials.Tierra1} position={[206.837, -2018.736, -1618.999]} rotation={[-1.521, 0.03, 1.803]} scale={27.753} />
      <mesh geometry={nodes.Icosphere015_Tierra1_0.geometry} material={materials.Tierra1} position={[401.638, -2638.47, -1442.201]} rotation={[-1.521, 0.03, 1.803]} scale={36.612} />
      <mesh geometry={nodes.Cube_Big_Tree_0.geometry} material={materials.Big_Tree} position={[187.291, 1305.72, 1019.177]} rotation={[-Math.PI / 2, 0, 0]} scale={52.965} />
      <mesh geometry={nodes.Cube001_Big_Tree_0.geometry} material={materials.Big_Tree} position={[430.585, 1031.105, -812.819]} rotation={[-Math.PI / 2, 0, 0]} scale={52.273} />
      <mesh geometry={nodes.Cube002_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-1255.125, 1376.139, 801.78]} rotation={[-Math.PI / 2, 0, 0]} scale={52.965} />
      <mesh geometry={nodes.Cube003_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-964.059, 1250.73, -984.651]} rotation={[-Math.PI / 2, 0, 0]} scale={52.965} />
      <mesh geometry={nodes.Cube004_Big_Tree_0.geometry} material={materials.Big_Tree} position={[1073.308, 476, -1727.951]} rotation={[-2.456, 0.53, -0.34]} scale={52.965} />
      <mesh geometry={nodes.Cube005_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-667.853, 1079.742, 1157.209]} rotation={[-1.266, -0.024, 2.336]} scale={48.775} />
      <mesh geometry={nodes.Cube006_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-1227.786, 1265.369, 5.543]} rotation={[-Math.PI / 2, 0, 0]} scale={39.527} />
      <mesh geometry={nodes.Cube007_Big_Tree_0.geometry} material={materials.Big_Tree} position={[785.31, 1184.33, -411.566]} rotation={[-1.766, 0.325, -1.15]} scale={52.965} />
      <mesh geometry={nodes.Cube008_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-504.716, 1363.164, -664.753]} rotation={[-Math.PI / 2, 0, -1.863]} scale={52.965} />
      <mesh geometry={nodes.Cube009_Big_Tree_0.geometry} material={materials.Big_Tree} position={[20.702, 1107.467, -1361.948]} rotation={[-1.718, 0.02, 1.358]} scale={44.654} />
      <mesh geometry={nodes.Cube010_Big_Tree_0.geometry} material={materials.Big_Tree} position={[314.288, 1308.768, 453.477]} rotation={[-Math.PI / 2, 0, -1.726]} scale={52.965} />
      <mesh geometry={nodes.Cube011_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-636.831, 1312.444, 451.204]} rotation={[-1.766, 0.325, -1.15]} scale={33.845} />
      <mesh geometry={nodes.Cube012_Big_Tree_0.geometry} material={materials.Big_Tree} position={[1005.933, 1111.603, 1107.272]} rotation={[-0.871, 0.189, -1.559]} scale={52.965} />
      <mesh geometry={nodes.Cube013_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-238.368, 1066.412, 1594.613]} rotation={[-Math.PI / 2, 0, 1.39]} scale={18.121} />
      <mesh geometry={nodes.Cube014_Big_Tree_0.geometry} material={materials.Big_Tree} position={[1098.51, 932.107, -798.184]} rotation={[-1.814, -0.291, 0.725]} scale={40.175} />
      <mesh geometry={nodes.Cube015_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-464.291, 726.691, 2871.26]} rotation={[-1.427, 0.743, 1.276]} scale={39.527} />
      <mesh geometry={nodes.Cube016_Big_Tree_0.geometry} material={materials.Big_Tree} position={[485.331, 1141.529, 1429.953]} rotation={[-1.443, 0.008, 0.066]} scale={52.965} />
      <mesh geometry={nodes.Cube017_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-168.62, 1174.718, -933.199]} rotation={[-Math.PI / 2, 0, 0]} scale={34.914} />
      <mesh geometry={nodes.Cube018_Big_Tree_0.geometry} material={materials.Big_Tree} position={[1360.169, 972.747, 205.664]} rotation={[-1.515, 0.256, -0.001]} scale={52.965} />
      <mesh geometry={nodes.Cylinder_Big_Tree_0.geometry} material={materials.Big_Tree} position={[-171.834, 1346.746, -33.5]} rotation={[-Math.PI / 2, 0, 0]} scale={205.394} />
      <mesh geometry={nodes.Cylinder001_Material_0.geometry} material={materials.Material} position={[-171.834, 1346.746, -33.5]} rotation={[-Math.PI / 2, 0, 0]} scale={205.394} />
      <mesh geometry={nodes.Icosphere029_cloud_0.geometry} material={materials.material_0} position={[-606.441, 1529.256, -1807.604]} rotation={[-Math.PI / 2, 0, -0.043]} scale={[208.043, 285.085, 208.043]} />
      <mesh geometry={nodes.Icosphere030_cloud_0.geometry} material={materials.material_0} position={[-1664.94, 1268.79, 1662.938]} rotation={[-Math.PI / 2, 0, -0.043]} scale={[130.79, 179.223, 130.79]} />
      <mesh geometry={nodes.Icosphere031_cloud_0.geometry} material={materials.material_0} position={[-1599.674, 1397.918, 1367.294]} rotation={[1.598, 0.56, 0.613]} scale={[38.489, 52.742, 38.489]} />
      <mesh geometry={nodes.Icosphere032_cloud_0.geometry} material={materials.material_0} position={[998.159, -547.073, -2483.669]} rotation={[1.598, 0.56, 0.613]} scale={[213.975, 293.213, 213.975]} />
      <mesh geometry={nodes.Icosphere033_cloud_0.geometry} material={materials.material_0} position={[646.511, -110.256, -2701.127]} rotation={[1.598, 0.56, 0.613]} scale={[107.868, 147.813, 107.868]} />
      <mesh geometry={nodes.Icosphere034_cloud_0.geometry} material={materials.material_0} position={[-509.417, 1744.961, -2076]} rotation={[-Math.PI / 2, 0, -1.193]} scale={[88.92, 121.848, 88.92]} />
      <mesh geometry={nodes.Icosphere035_cloud_0.geometry} material={materials.material_0} position={[931.576, -1178.033, 2149.865]} rotation={[-0.769, 0.211, 0.801]} scale={[73.135, 100.218, 73.135]} />
      <mesh geometry={nodes.Icosphere021_Brush_0.geometry} material={materials.Brush} position={[768.458, 1025.809, 536.197]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 144.932, 100]} />
      <mesh geometry={nodes.Icosphere022_Brush_0.geometry} material={materials.Brush} position={[-888.99, 1131.284, -485.981]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 144.932, 100]} />
      <mesh geometry={nodes.Icosphere023_Brush_0.geometry} material={materials.Brush} position={[681.698, 860.875, -1158.305]} rotation={[-Math.PI / 2, 0, 0.353]} scale={[100, 144.932, 100]} />
      <mesh geometry={nodes.Icosphere024_Brush_0.geometry} material={materials.Brush} position={[-361.563, 1140.425, 997.768]} rotation={[-Math.PI / 2, 0, 1.09]} scale={[62.069, 89.958, 62.069]} />
      <mesh geometry={nodes.Icosphere025_Brush_0.geometry} material={materials.Brush} position={[189.047, 1021.445, -1077.163]} rotation={[-Math.PI / 2, 0, 0]} scale={[62.069, 89.958, 62.069]} />
      <mesh geometry={nodes.Icosphere026_Brush_0.geometry} material={materials.Brush} position={[-1576.419, 1065.564, 304.546]} rotation={[-Math.PI / 2, 0, 0]} scale={[50.67, 73.437, 50.67]} />
      <mesh geometry={nodes.Icosphere027_Brush_0.geometry} material={materials.Brush} position={[-440.381, 1149.015, 968.845]} rotation={[-Math.PI / 2, 0, 1.09]} scale={[62.069, 89.958, 62.069]} />
      <mesh geometry={nodes.Icosphere028_Brush_0.geometry} material={materials.Brush} position={[-834.763, 1140.918, -408.408]} rotation={[-Math.PI / 2, 0, 1.09]} scale={[68.263, 81.283, 50.769]} />
      <mesh geometry={nodes.Icosphere016_Rock_0.geometry} material={materials.Rock} position={[860.936, 1030.725, 254.648]} rotation={[-Math.PI / 2, 0, 0]} scale={[49.055, 64.97, 49.055]} />
      <mesh geometry={nodes.Icosphere017_Rock_0.geometry} material={materials.Rock} position={[-317.11, 1186.92, 525.644]} rotation={[-Math.PI / 2, 0, 0]} scale={[49.055, 64.97, 49.055]} />
      <mesh geometry={nodes.Icosphere018_Rock_0.geometry} material={materials.Rock} position={[-510.015, 1048.911, -1202.221]} rotation={[-Math.PI / 2, 0, 0]} scale={[22.453, 29.737, 22.453]} />
      <mesh geometry={nodes.Icosphere019_Rock_0.geometry} material={materials.Rock} position={[448.412, 1024.036, -745.269]} rotation={[-Math.PI / 2, 0, 0]} scale={[22.453, 29.737, 22.453]} />
      <mesh geometry={nodes.Icosphere020_Rock_0.geometry} material={materials.Rock} position={[-999.216, 1102.997, 1009.985]} rotation={[-Math.PI / 2, 0, 0]} scale={[22.453, 29.737, 22.453]} />
      <mesh geometry={nodes.Sphere_WIII_0.geometry} material={materials.WIII} position={[795.478, 1046.882, -607.148]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere001_WIII_0.geometry} material={materials.WIII} position={[502.503, 1416.577, 1173.472]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere002_WIII_0.geometry} material={materials.WIII} position={[-206.777, 1227.701, -1443.843]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere003_WIII_0.geometry} material={materials.WIII} position={[-385.602, 1681.585, 768.914]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere004_WIII_0.geometry} material={materials.WIII} position={[-1263.757, 1898.844, 142.342]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere005_WIII_0.geometry} material={materials.WIII} position={[-596.26, 1651.512, -500.189]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere006_WIII_0.geometry} material={materials.WIII} position={[1805.024, -1076.091, 1070.613]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere007_WIII_0.geometry} material={materials.WIII} position={[-939.834, -68.674, 3304.8]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere008_WIII_0.geometry} material={materials.WIII} position={[-76.323, -1153.119, -1083.362]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere009_WIII_0.geometry} material={materials.WIII} position={[1601.355, 772.378, 778.573]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere010_WIII_0.geometry} material={materials.WIII} position={[1853.022, -362.281, -704.556]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere011_WIII_0.geometry} material={materials.WIII} position={[-675.565, -623.435, -1613.035]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere012_WIII_0.geometry} material={materials.WIII} position={[-1988.556, 251.768, -535.887]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere013_WIII_0.geometry} material={materials.WIII} position={[-1824.808, -955.413, -1290.953]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
      <mesh geometry={nodes.Sphere014_WIII_0.geometry} material={materials.WIII} position={[16.976, 493.967, -2034.595]} rotation={[-Math.PI / 2, 0, 0]} scale={9.685} />
    </group>
  )
}

useGLTF.preload('/magic_forest.glb')
