/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RiZoRuS77 (https://sketchfab.com/RiZoRuS77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-magic-hat-3807a50367fa444187d70ef02f7e0e71
Title: Stylized Magic hat
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export default function Hat(props) {
  const { nodes, materials } = useGLTF('/models/magic_hat.glb')

  const modelRef=useRef()

  useFrame(() => {
    modelRef.current.position.y=Math.sin(Date.now()/500)/10 * 1.3;
  })

  return (
    <group {...props} dispose={null}
      scale={[0.025, 0.02, 0.015]}
      position={[0, 2, -0.5]}
      ref={modelRef}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Magic_Hat_Material_1001}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/magic_hat.glb')