/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fridge (https://sketchfab.com/youssefdarwish01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-magic-staff-428f67250aa94f9d9b52dc3e919ab408
Title: Wooden Magic Staff
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Staff(props) {
  const { nodes, materials } = useGLTF('/models/magic_staff.glb')

  const modelRef = useRef();

 useFrame(() => {

    modelRef.current.position.y=Math.sin(Date.now()/500)/10 * 1.3;
 })


  return (
    <group {...props} dispose={null}
        scale={[0.8,0.7,0.6]}
        position={[0,0,0]}
        ref={modelRef}
        rotation={[0, 4.5, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Staff_MatMain}
        position={[0, 3.813, -0.802]}
      />
    </group>
  )
}

useGLTF.preload('/models/magic_staff.glb')
