
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Uricaro97 (https://sketchfab.com/Uricaro97)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-stylize-wooden-log-10a059259fa947ddaa8eb4190e4bd2a5
Title: Low Poly Stylize Wooden log
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Wood(props) {
  const { nodes, materials } = useGLTF('/models/wood.glb')

   const modelRef = useRef();
  
   useFrame(() => {
  
      modelRef.current.position.y=Math.sin(Date.now()/500)/10 * 1.3;
   })
  
  return (
    <group {...props} dispose={null}
        scale={[2,2,2]}
        position={[0,0.7,0.6]}
        rotation={[0.45,-1.1,0]}
        ref={modelRef}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.351}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_Material001_0.geometry}
            material={materials['Material.001']}
            position={[2.078, 99.509, 0.845]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.L_L_0.geometry}
            material={materials.material}
            position={[98.047, 197.696, 23.608]}
            scale={34.632}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/wood.glb')